# Generated by Django 3.0.3 on 2021-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_id', models.IntegerField()),
                ('School_id', models.IntegerField()),
                ('Start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_id', models.IntegerField()),
                ('School_name', models.CharField(max_length=100)),
                ('School_address', models.CharField(max_length=200)),
                ('School_location', models.CharField(max_length=100)),
            ],
        ),
    ]
